kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: main-obr-embedded-
spec:
  params:
  - name: distBranch
    value: main
  - name: version
    value: 0.17.0
  pipelineRef:
    name: obr-generic-build
  serviceAccountName: build-bot
  resources:
  - name: git-docker
    resourceRef:
      name: git-docker-main
  podTemplate:
    nodeSelector:
      beta.kubernetes.io/arch: amd64
      platform: hdc
