kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  name: main-galasabld-build
spec:
  params:
  - name: distBranch
    value: main
  - name: version
    value: 0.16.0
  pipelineRef:
    name: galasabld-build
  serviceAccountName: build-bot
  resources:
  - name: git-tekton
    resourceRef:
      name: galasa-tekton-build
  podTemplate:
    nodeSelector:
      beta.kubernetes.io/arch: amd64
      platform: hdc
