#
# Licensed Materials - Property of IBM
# 
# (c) Copyright IBM Corp. 2021.
#
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: recycle-prod-
  namespace: galasa-tekton
spec:
  pipelineRef:
    name: recycle-prod
  serviceAccountName: build-bot
  resources:
  podTemplate:
    nodeSelector:
      beta.kubernetes.io/arch: amd64
      platform: hdc
