#
# Licensed Materials - Property of IBM
# 
# (c) Copyright IBM Corp. 2021.
#
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: openapi-main-build-
  namespace: galasa-tekton
spec:
  pipelineRef:
    name: openapi-build
  serviceAccountName: build-bot
  resources:
  - name: git-openapi
    resourceRef:
      name: git-openapi-main
  - name: git-openapi-go
    resourceRef:
      name: git-openapi-go-main
  podTemplate:
    nodeSelector:
      beta.kubernetes.io/arch: amd64
      platform: hdc      
