kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: galasa-build-engine-build-
spec:
  pipelineRef:
    name: galasa-build-engine-build
  serviceAccountName: build-bot
  resources:
  - name: git-tekton-build
    resourceRef:
      name: galasa-tekton-build
  podTemplate:
    nodeSelector:
      beta.kubernetes.io/arch: amd64
      platform: hdc
