kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: main-obr-
spec:
  params:
  - name: distBranch
    value: main
  - name: version
    value: 0.17.0
  pipelineRef:
    name: obr-repo-build2
  serviceAccountName: build-bot
  resources:
  - name: git-obr
    resourceRef:
      name: git-obr-mike
  podTemplate:
    nodeSelector:
      beta.kubernetes.io/arch: amd64
      platform: hdc
    volumes:
    - name: mavengpg
      secret:
        secretName: mavengpg
