kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: snapshot-galasa-
spec:
  params:
  - name: distBranch
    value: prod
  - name: oldBranch
    value: main
  - name: version
    value: 0.16.0
  pipelineRef:
    name: snapshot-galasa
  serviceAccountName: build-bot
  resources:
  - name: git-tekton
    resourceRef:
      name: galasa-tekton-build
  podTemplate:
    nodeSelector:
      beta.kubernetes.io/arch: amd64
      platform: hdc
