kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: main-javadoc-
spec:
  params:
  - name: distBranch
    value: main
  - name: version
    value: 0.16.0
  pipelineRef:
    name: javadoc-build
  serviceAccountName: build-bot
  resources:
  - name: git-obr
    resourceRef:
      name: git-obr-main
  podTemplate:
    nodeSelector:
      beta.kubernetes.io/arch: amd64
      platform: hdc
