kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: main-managers-
spec:
  params:
  - name: distBranch
    value: main
  - name: version
    value: 0.16.0
  - name: jacocoEnabled
    value: "true"
  pipelineRef:
    name: managers-repo-build
  serviceAccountName: build-bot
  resources:
  - name: git-managers
    resourceRef:
      name: git-managers-main
  podTemplate:
    nodeSelector:
      beta.kubernetes.io/arch: amd64
      platform: hdc
