kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: obr-repo-build-
spec:
  params:
  - name: branch
    value: main
  - name: version
    value: 0.16.0
  pipelineRef:
    name: obr-repo-build
  serviceAccountName: build-bot
  resources:
  - name: git-obr
    resourceRef:
      name: git-obr-main
  podTemplate:
    nodeSelector:
      beta.kubernetes.io/arch: amd64
