#
# Licensed Materials - Property of IBM
# 
# (c) Copyright IBM Corp. 2021.
#
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: main-runtime-
  namespace: galasa-tekton
spec:
  params:
  - name: distBranch
    value: main
  - name: mavenVersion
    value: 0.15.0
  - name: jacocoEnabled
    value: "true"
  pipelineRef:
    name: runtime-build
  serviceAccountName: build-bot
  resources:
  - name: git-framework
    resourceRef:
      name: git-framework-main
  - name: git-extensions
    resourceRef:
      name: git-extensions-main
  - name: git-managers
    resourceRef:
      name: git-managers-main
  - name: git-docker
    resourceRef:
      name: git-docker-main
  podTemplate:
    nodeSelector:
      beta.kubernetes.io/arch: amd64
      platform: hdc
    volumes:
    - name: gpgkey
      secret:
        secretName: gpgkey
    - name: gpggradle
      secret:
        secretName: gpggradle
    - name: mavengpg
      secret:
        secretName: mavengpg
  workspaces:
  - name: git-workspace
    volumeClaimTemplate:
      spec:
        storageClassName: rbd
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
