apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mvp-build
spec:
  resources:
    inputs:
      - name: git-isolated
        type: git
  params:
  - name: branch
    type: string
  - name: version
    type: string
  - name: mavenCentralRepo
    type: string
    default: https://repo.maven.apache.org/maven2/
  - name: runtimeSourceRepo
    type: string
    default: https://repo.maven.apache.org/maven2/
  - name: simplatformSourceRepo
    type: string
    default: https://repo.maven.apache.org/maven2/
  - name: eclipseSourceRepo
    type: string
    default: http://download.eclipse.org/releases/photon
  - name: dockerRepo
    type: string
    default: nexus.cics-ts.hur.hdclab.intranet.ibm.com:8080
  - name: mavenBaseVersion
    type: string
    default: 0.16.0
  steps:
  - name: maven-build-mvp1
    workingDir: /workspace/git-isolated/mvp
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - mvn
    - -Dgpg.skip=true
    - -Dgalasa.target.repo=file:target/isolated/maven
    - -Dgalasa.runtime.repo=$(params.runtimeSourceRepo)
    - -Dgalasa.simplatform.repo=$(params.simplatformSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - -Dgalasa.eclipse.repo=$(params.eclipseSourceRepo)
    - --settings
    - /workspace/git-isolated/settings.xml
    - -B
    - -e
    - -fae
    - process-sources
  - name: maven-build-mvp2
    workingDir: /workspace/git-isolated/mvp
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - mvn
    - -Dgpg.skip=true
    - -Dgalasa.target.repo=file:target/isolated/maven
    - -Dgalasa.runtime.repo=$(params.runtimeSourceRepo)
    - -Dgalasa.simplatform.repo=$(params.simplatformSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - -Dgalasa.eclipse.repo=$(params.eclipseSourceRepo)
    - --settings
    - /workspace/git-isolated/settings.xml
    - -B
    - -e
    - -fae
    - -f
    - pom2.xml
    - process-sources
  - name: maven-build-mvp3
    workingDir: /workspace/git-isolated/mvp
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - mvn
    - -Dgpg.skip=true
    - -Dgalasa.target.repo=file:target/isolated/maven
    - -Dgalasa.runtime.repo=$(params.runtimeSourceRepo)
    - -Dgalasa.simplatform.repo=$(params.simplatformSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - -Dgalasa.eclipse.repo=$(params.eclipseSourceRepo)
    - --settings
    - /workspace/git-isolated/settings.xml
    - -B
    - -e
    - -fae
    - -f
    - pom3.xml
    - process-sources
  - name: maven-build-mvp4
    workingDir: /workspace/git-isolated/mvp
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - mvn
    - -Dgpg.skip=true
    - -Dgalasa.target.repo=file:target/isolated/maven
    - -Dgalasa.runtime.repo=$(params.runtimeSourceRepo)
    - -Dgalasa.simplatform.repo=$(params.simplatformSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - -Dgalasa.eclipse.repo=$(params.eclipseSourceRepo)
    - --settings
    - /workspace/git-isolated/settings.xml
    - -B
    - -e
    - -fae
    - -f
    - pom4.xml
    - process-sources
  - name: maven-build-mvp5
    workingDir: /workspace/git-isolated/mvp
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - mvn
    - -Dgpg.skip=true
    - -Dgalasa.target.repo=file:target/isolated/maven
    - -Dgalasa.runtime.repo=$(params.runtimeSourceRepo)
    - -Dgalasa.simplatform.repo=$(params.simplatformSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - -Dgalasa.eclipse.repo=$(params.eclipseSourceRepo)
    - --settings
    - /workspace/git-isolated/settings.xml
    - -B
    - -e
    - -fae
    - -f
    - pom5.xml
    - process-sources
  - name: maven-build-mvp6
    workingDir: /workspace/git-isolated/mvp
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - mvn
    - -Dgpg.skip=true
    - -Dgalasa.target.repo=file:target/isolated/maven
    - -Dgalasa.runtime.repo=$(params.runtimeSourceRepo)
    - -Dgalasa.simplatform.repo=$(params.simplatformSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - -Dgalasa.eclipse.repo=$(params.eclipseSourceRepo)
    - --settings
    - /workspace/git-isolated/settings.xml
    - -B
    - -e
    - -fae
    - -f
    - pom6.xml
    - process-sources
  - name: docker-build-mvp-image
    workingDir: /workspace/git-isolated/mvp
    image: $(params.dockerRepo)/library/kaniko-executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    command:
    - /kaniko/executor
    - --dockerfile=./Dockerfile
    - --context=/workspace/git-isolated/mvp
    - --destination=$(params.dockerRepo)/galasadev/galasa-mvp:$(params.version)-$(params.branch)
    - --oci-layout-path=/workspace/git-isolated/mvp/image-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --single-snapshot
    - --verbosity=info
    - --build-arg=dockerRepository=$(params.dockerRepo)
  - name: docker-tar-mvp-image
    workingDir: /workspace/git-isolated/mvp
    image: $(params.dockerRepo)/library/kaniko-executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    command:
    - /kaniko/executor
    - --no-push
    - --tarPath
    - /workspace/git-isolated/mvp/target/isolated/isolated.tar
    - --dockerfile=./Dockerfile
    - --context=/workspace/git-isolated/mvp
    - --destination=galasadev/galasa-mvp:$(params.version)-$(params.branch)
    - --oci-layout-path=/workspace/git-isolated/mvp/image-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --single-snapshot
    - --verbosity=info
    - --build-arg=dockerRepository=$(params.dockerRepo)
  - name: maven-build-mvp-zip
    workingDir: /workspace/git-isolated/mvp
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - mvn
    - -Dgpg.skip=true
    - -Dgalasa.release.repo=file:/workspace/git-isolated/mvp/repo
    - -Dgalasa.runtime.repo=$(params.runtimeSourceRepo)
    - -Dgalasa.simplatform.repo=$(params.simplatformSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - -Dgalasa.eclipse.repo=$(params.eclipseSourceRepo)
    - --settings
    - /workspace/git-isolated/settings.xml
    - -B
    - -e
    - -fae
    - -f
    - pomZip.xml
    - deploy
  - name: docker-build-mvp-maven-image
    workingDir: /workspace/git-isolated/mvp
    image: $(params.dockerRepo)/library/kaniko-executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    command:
    - /kaniko/executor
    - --dockerfile=./DockerfileZip
    - --context=/workspace/git-isolated/mvp
    - --destination=$(params.dockerRepo)/galasadev/galasa-maven-mvp:$(params.version)-$(params.branch)
    - --oci-layout-path=/workspace/git-isolated/mvp/image-maven-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --single-snapshot
    - --verbosity=info
    - --build-arg=dockerRepository=$(params.dockerRepo)
    - --build-arg=baseVersion=$(params.mavenBaseVersion)
    - --build-arg=branch=$(params.branch)
