apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gradle-repo-build
spec:
  resources:
    inputs:
      - name: git-gradle
        type: git
  params:
  - name: distBranch
    type: string
  - name: version
    type: string
  - name: mavenBaseVersion
    type: string
    default: 0.16.0
  - name: mavenCentralRepo
    type: string
    default: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
  - name: mavenSourceRepo
    type: string
    default: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
  - name: dockerRepo
    type: string
    default: nexus.cics-ts.hur.hdclab.intranet.ibm.com:8080
  - name: noPush
    type: string
    default: ""
  - name: jacocoEnabled
    type: string
    default: "false"
  - name: isRelease
    type: string
    default: "false"
  results:
  - name: image
    description: The image produced by this build
  steps:
  - name: get-commit
    workingDir: /workspace/git-gradle
    image: $(params.dockerRepo)/galasa/galasa-build
    script: |
      #!/bin/sh
      set +e
      COMMIT="$(git log --format="%H" -n 1)"
      echo $COMMIT > /workspace/git-gradle/docker/gradle.githash
      echo commit is $COMMIT
  - name: gradle-build
    workingDir: /workspace/git-gradle
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - gradle
    - --no-daemon
    - --console 
    - plain
    - -PsourceMaven=$(params.mavenSourceRepo)
    - -PcentralMaven=$(params.mavenCentralRepo)
    - -PtargetMaven=/workspace/git-gradle/docker/repo
    - -PjacocoEnabled=$(params.jacocoEnabled)
    - -PisRelease=$(params.isRelease)
    - publish
  - name: docker-build
    workingDir: /workspace/git-gradle/docker
    image: $(params.dockerRepo)/library/kaniko-executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    command:
    - /kaniko/executor
    - --dockerfile=./Dockerfile
    - --context=/workspace/git-gradle/docker
    - --destination=$(params.dockerRepo)/galasadev/galasa-maven-gradle:$(params.version)-$(params.distBranch)
    - $(params.noPush)
    - --oci-layout-path=/workspace/git-gradle/docker/image-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --single-snapshot
    - --verbosity=info
    - --build-arg=dockerRepository=$(params.dockerRepo)
    - --build-arg=baseVersion=$(params.mavenBaseVersion)
    - --build-arg=branch=$(params.distBranch)
  - name: report-result
    image: $(params.dockerRepo)/galasa/galasa-build
    script: |
      #!/bin/sh
      set +e
      echo "galasa-maven-gradle:$(params.version)-$(params.distBranch)" > /tekton/results/image
