apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openapi-update-github
spec:
  workspaces:
  - name: ws
    mountPath: /workspace
  steps:
  - name: ls1
    workingDir: /workspace/openapi-go
    image: nexus.cics-ts.hur.hdclab.intranet.ibm.com:8080/galasa/galasa-build
    command:
    - ls
    - -la
  - name: git-email
    workingDir: /workspace/openapi-go
    image: nexus.cics-ts.hur.hdclab.intranet.ibm.com:8080/galasa/galasa-build
    command:
    - git 
    - config
    - user.email
    - "'cicsdeliverytest@uk.com'"
  - name: git-user
    workingDir: /workspace/openapi-go
    image: nexus.cics-ts.hur.hdclab.intranet.ibm.com:8080/galasa/galasa-build
    command:
    - git 
    - config
    - user.name
    - "'Automation'"
  - name: git-add
    workingDir: /workspace/openapi-go
    image: nexus.cics-ts.hur.hdclab.intranet.ibm.com:8080/galasa/galasa-build
    command:
    - git 
    - add
    - -v
    - '.'
  - name: git-status1
    workingDir: /workspace/openapi-go
    image: nexus.cics-ts.hur.hdclab.intranet.ibm.com:8080/galasa/galasa-build
    command:
    - git 
    - status
    - "."
  - name: git-commit
    workingDir: /workspace/openapi-go
    image: nexus.cics-ts.hur.hdclab.intranet.ibm.com:8080/galasa/galasa-build
    command:
    - git 
    - commit
    - -m
    - "'openapi generate update'"
  - name: git-status2
    workingDir: /workspace/openapi-go
    image: nexus.cics-ts.hur.hdclab.intranet.ibm.com:8080/galasa/galasa-build
    command:
    - git 
    - status
    - "."
  - name: git-config
    workingDir: /workspace/openapi-go
    image: nexus.cics-ts.hur.hdclab.intranet.ibm.com:8080/galasa/galasa-build
    command:
    - ls
    - -al
    - /root
  - name: git-config2
    workingDir: /workspace/openapi-go
    image: nexus.cics-ts.hur.hdclab.intranet.ibm.com:8080/galasa/galasa-build
    command:
    - cat
    - /root/.gitconfig
  - name: git-config3
    workingDir: /workspace/openapi-go
    image: nexus.cics-ts.hur.hdclab.intranet.ibm.com:8080/galasa/galasa-build
    command:
    - cat
    - /root/.git-credentials
  - name: git-push
    workingDir: /workspace/openapi-go
    image: nexus.cics-ts.hur.hdclab.intranet.ibm.com:8080/galasa/galasa-build
    command:
    - git 
    - push
    - origin
    - main    
