apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: galasa-build-engine-build
spec:
  resources:
    inputs:
      - name: git-tekton-build
        type: git
  params:
  - name: dockerRepo
    type: string
    default: nexus.cics-ts.hur.hdclab.intranet.ibm.com:8080
  steps:
  - name: docker-build
    workingDir: /workspace/git-tekton-build/docker/galasa-build
    image: $(params.dockerRepo)/library/kaniko-executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    command:
    - /kaniko/executor
    - --dockerfile=./Dockerfile
    - --context=/workspace/git-tekton-build/docker/galasa-build
    - --destination=$(params.dockerRepo)/galasa/galasa-build:latest
    - --oci-layout-path=/workspace/git-tekton-build/docker/galasa-build/image-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --verbosity=trace