apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: isolated-build
spec:
  resources:
    inputs:
      - name: git-isolated
        type: git
      - name: git-obr
        type: git
  params:
  - name: distBranch
    type: string
  - name: version
    type: string
  - name: mavenCentralRepo
    type: string
    default: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
  - name: runtimeSourceRepo
    type: string
    default: https://repo.maven.apache.org/maven2/
  - name: simplatformSourceRepo
    type: string
    default: https://repo.maven.apache.org/maven2/
  - name: eclipseSourceRepo
    type: string
    default: http://download.eclipse.org/releases/photon
  - name: javadocSourceRepo
    type: string
    default: https://repo.maven.apache.org/maven2/
  - name: docsSourceRepo
    type: string
    default: https://repo.maven.apache.org/maven2/
  - name: dockerRepo
    type: string
    default: nexus.cics-ts.hur.hdclab.intranet.ibm.com:8080
  - name: mavenBaseVersion
    type: string
    default: 0.16.0
  - name: noPush
    type: string
    default: ""
  steps:
  - name: generate-pom
    workingDir: /workspace/git-isolated/full
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - galasabld 
    - template 
    - --releaseMetadata
    - /workspace/git-obr/release.yaml 
    - --template
    - pom.template 
    - --output
    - pom.xml 
    - --isolated
  - name: maven-build-isolated1
    workingDir: /workspace/git-isolated/full
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - mvn
    - -Dgpg.skip=true
    - -Dgalasa.target.repo=file:target/isolated/maven
    - -Dgalasa.runtime.repo=$(params.runtimeSourceRepo)
    - -Dgalasa.simplatform.repo=$(params.simplatformSourceRepo)
    - -Dgalasa.javadoc.repo=$(params.javadocSourceRepo)
    - -Dgalasa.docs.repo=$(params.docsSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - -Dgalasa.eclipse.repo=$(params.eclipseSourceRepo)
    - --settings
    - /workspace/git-isolated/settings.xml
    - -B
    - -e
    - -fae
    - -f
    - pom.xml
    - process-sources
  - name: maven-build-isolated2
    workingDir: /workspace/git-isolated/full
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - mvn
    - -Dgpg.skip=true
    - -Dgalasa.target.repo=file:target/isolated/maven
    - -Dgalasa.runtime.repo=$(params.runtimeSourceRepo)
    - -Dgalasa.simplatform.repo=$(params.simplatformSourceRepo)
    - -Dgalasa.javadoc.repo=$(params.javadocSourceRepo)
    - -Dgalasa.docs.repo=$(params.docsSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - -Dgalasa.eclipse.repo=$(params.eclipseSourceRepo)
    - --settings
    - /workspace/git-isolated/settings.xml
    - -B
    - -e
    - -fae
    - -f
    - pom2.xml
    - process-sources
  - name: maven-build-isolated3
    workingDir: /workspace/git-isolated/full
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - mvn
    - -Dgpg.skip=true
    - -Dgalasa.target.repo=file:target/isolated/maven
    - -Dgalasa.runtime.repo=$(params.runtimeSourceRepo)
    - -Dgalasa.simplatform.repo=$(params.simplatformSourceRepo)
    - -Dgalasa.javadoc.repo=$(params.javadocSourceRepo)
    - -Dgalasa.docs.repo=$(params.docsSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - -Dgalasa.eclipse.repo=$(params.eclipseSourceRepo)
    - --settings
    - /workspace/git-isolated/settings.xml
    - -B
    - -e
    - -fae
    - -f
    - pom3.xml
    - process-sources
  - name: maven-build-isolated4
    workingDir: /workspace/git-isolated/full
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - mvn
    - -Dgpg.skip=true
    - -Dgalasa.target.repo=file:target/isolated/maven
    - -Dgalasa.runtime.repo=$(params.runtimeSourceRepo)
    - -Dgalasa.simplatform.repo=$(params.simplatformSourceRepo)
    - -Dgalasa.javadoc.repo=$(params.javadocSourceRepo)
    - -Dgalasa.docs.repo=$(params.docsSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - -Dgalasa.eclipse.repo=$(params.eclipseSourceRepo)
    - --settings
    - /workspace/git-isolated/settings.xml
    - -B
    - -e
    - -fae
    - -f
    - pom4.xml
    - process-sources
  - name: maven-build-isolated5
    workingDir: /workspace/git-isolated/full
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - mvn
    - -Dgpg.skip=true
    - -Dgalasa.target.repo=file:target/isolated/maven
    - -Dgalasa.runtime.repo=$(params.runtimeSourceRepo)
    - -Dgalasa.simplatform.repo=$(params.simplatformSourceRepo)
    - -Dgalasa.javadoc.repo=$(params.javadocSourceRepo)
    - -Dgalasa.docs.repo=$(params.docsSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - -Dgalasa.eclipse.repo=$(params.eclipseSourceRepo)
    - --settings
    - /workspace/git-isolated/settings.xml
    - -B
    - -e
    - -fae
    - -f
    - pom5.xml
    - process-sources
  - name: maven-build-isolated6
    workingDir: /workspace/git-isolated/full
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - mvn
    - -Dgpg.skip=true
    - -Dgalasa.target.repo=file:target/isolated/maven
    - -Dgalasa.runtime.repo=$(params.runtimeSourceRepo)
    - -Dgalasa.simplatform.repo=$(params.simplatformSourceRepo)
    - -Dgalasa.javadoc.repo=$(params.javadocSourceRepo)
    - -Dgalasa.docs.repo=$(params.docsSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - -Dgalasa.eclipse.repo=$(params.eclipseSourceRepo)
    - --settings
    - /workspace/git-isolated/settings.xml
    - -B
    - -e
    - -fae
    - -f
    - pom6.xml
    - process-sources
  - name: maven-build-javadoc
    workingDir: /workspace/git-isolated/full
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - mvn
    - -Dgpg.skip=true
    - -Dgalasa.target.repo=file:target/isolated/maven
    - -Dgalasa.runtime.repo=$(params.runtimeSourceRepo)
    - -Dgalasa.simplatform.repo=$(params.simplatformSourceRepo)
    - -Dgalasa.javadoc.repo=$(params.javadocSourceRepo)
    - -Dgalasa.docs.repo=$(params.docsSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - -Dgalasa.eclipse.repo=$(params.eclipseSourceRepo)
    - --settings
    - /workspace/git-isolated/settings.xml
    - -B
    - -e
    - -fae
    - -f
    - pomJavaDoc.xml
    - process-sources
  - name: maven-build-docs
    workingDir: /workspace/git-isolated/full
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - mvn
    - -Dgpg.skip=true
    - -Dgalasa.target.repo=file:target/isolated/maven
    - -Dgalasa.runtime.repo=$(params.runtimeSourceRepo)
    - -Dgalasa.simplatform.repo=$(params.simplatformSourceRepo)
    - -Dgalasa.javadoc.repo=$(params.javadocSourceRepo)
    - -Dgalasa.docs.repo=$(params.docsSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - -Dgalasa.eclipse.repo=$(params.eclipseSourceRepo)
    - --settings
    - /workspace/git-isolated/settings.xml
    - -B
    - -e
    - -fae
    - -f
    - pomDocs.xml
    - process-sources
  - name: copy-text-files
    workingDir: /workspace/git-isolated/full
    image: $(params.dockerRepo)/galasa/galasa-build
    script: |
      #!/bin/sh
      set +e
      cp -v resources/* target/isolated/
  - name: docker-build-isolated-image
    workingDir: /workspace/git-isolated/full
    image: $(params.dockerRepo)/library/kaniko-executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    command:
    - /kaniko/executor
    - --dockerfile=./Dockerfile
    - --context=/workspace/git-isolated/full
    - --destination=$(params.dockerRepo)/galasadev/galasa-isolated:$(params.version)-$(params.distBranch)
    - --oci-layout-path=/workspace/git-isolated/full/image-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --single-snapshot
    - --verbosity=info
    - --build-arg=dockerRepository=$(params.dockerRepo)
  - name: docker-tar-isolated-image
    workingDir: /workspace/git-isolated/full
    image: $(params.dockerRepo)/library/kaniko-executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    command:
    - /kaniko/executor
    - --no-push
    - --tarPath
    - /workspace/git-isolated/full/target/isolated/isolated.tar
    - --dockerfile=./Dockerfile
    - --context=/workspace/git-isolated/full
    - --destination=galasadev/galasa-isolated:$(params.version)-$(params.distBranch)
    - --oci-layout-path=/workspace/git-isolated/full/image-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --single-snapshot
    - --verbosity=info
    - --build-arg=dockerRepository=$(params.dockerRepo)
  - name: maven-build-isolated-zip
    workingDir: /workspace/git-isolated/full
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - mvn
    - -Dgpg.skip=true
    - -Dgalasa.release.repo=file:/workspace/git-isolated/full/repo
    - -Dgalasa.runtime.repo=$(params.runtimeSourceRepo)
    - -Dgalasa.simplatform.repo=$(params.simplatformSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - -Dgalasa.eclipse.repo=$(params.eclipseSourceRepo)
    - --settings
    - /workspace/git-isolated/settings.xml
    - -B
    - -e
    - -fae
    - -f
    - pomZip.xml
    - deploy
  - name: docker-build-isolated-maven-image
    workingDir: /workspace/git-isolated/full
    image: $(params.dockerRepo)/library/kaniko-executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    command:
    - /kaniko/executor
    - --dockerfile=./DockerfileZip
    - --context=/workspace/git-isolated/full
    - --destination=$(params.dockerRepo)/galasadev/galasa-maven-isolated:$(params.version)-$(params.distBranch)
    - $(params.noPush)
    - --oci-layout-path=/workspace/git-isolated/full/image-maven-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --single-snapshot
    - --verbosity=info
    - --build-arg=dockerRepository=$(params.dockerRepo)
    - --build-arg=baseVersion=$(params.mavenBaseVersion)
    - --build-arg=branch=$(params.distBranch)
