apiVersion: v1
kind: Service
metadata:
  name: maven-{{ .Release.Name }}-isolated
  labels:
    app: maven-{{ .Release.Name }}-isolated
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: maven-{{ .Release.Name }}-isolated