{{- if .Values.ingress.enabled }}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: maven-{{ .Release.Name }}-isolated
  annotations:
    kubernetes.io/ingress.class: nginx-cit-insecure
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  rules:
    - http:
        paths:
          - path: /galasadev/{{ .Release.Name}}/maven/isolated
            backend:
              serviceName: maven-{{ .Release.Name}}-isolated
              servicePort: 80
{{- end }}