apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-gradle-main
spec:
  type: git
  params:
  - name: revision
    value: main
  - name: url
    value: https://github.com/galasa-dev/gradle
