apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: openapi-go-main-git
spec:
  type: git
  params:
  - name: revision
    value: main
  - name: refspec
    value: +refs/heads/main:refs/heads/main
  - name: url
    value: https://github.com/galasa-dev/openapi-go
