#
# Licensed Materials - Property of IBM
# 
# (c) Copyright IBM Corp. 2021.
#
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: recycle-deployment
  namespace: galasa-tekton
spec:
  params:
  - name: namespace
    type: string
  - name: deployment
    type: string
  - name: dockerRepo
    type: string
    default: nexus.cics-ts.hur.hdclab.intranet.ibm.com:8080
  steps:
  - name: start-recycle
    workingDir: /workspace/git-gradle
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - kubectl
    - -n
    - $(params.namespace)
    - rollout
    - restart
    - deployment/$(params.deployment)
  - name: wait-recycle
    workingDir: /workspace/git-gradle
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - kubectl
    - -n
    - $(params.namespace)
    - rollout
    - status
    - deployment/$(params.deployment)
    - -w
    - --timeout=3m
