kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-builder
subjects:
roleRef:
  kind: Role
  name: tekton-builder
  apiGroup: rbac.authorization.k8s.io
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidc:cics_k8s_galasa_dev
