kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-build
subjects:
- kind: ServiceAccount
  name: tekton-pipelines-controller
  namespace: tekton
- kind: ServiceAccount
  name: build-bot
  namespace: galasa-dev-{{ .Release.Name }}
roleRef:
  kind: Role
  name: tekton-build
  apiGroup: rbac.authorization.k8s.io
