# Default values for galasa-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  replicaCount: 2
  pullPolicy: Always

eclipse:
  repository: harbor-cicsk8s.hursley.ibm.com/galasadev/galasa-maven-eclipse

extensions:
  repository: harbor-cicsk8s.hursley.ibm.com/galasadev/galasa-maven-extensions
 
framework:
  repository: harbor-cicsk8s.hursley.ibm.com/galasadev/galasa-maven-framework

gradle:
  repository: harbor-cicsk8s.hursley.ibm.com/galasadev/galasa-maven-gradle

isolated:
  repository: harbor-cicsk8s.hursley.ibm.com/galasadev/galasa-maven-isolated

managers:
  repository: harbor-cicsk8s.hursley.ibm.com/galasadev/galasa-maven-managers

maven:
  repository: harbor-cicsk8s.hursley.ibm.com/galasadev/galasa-maven-maven

mvp:
  repository: harbor-cicsk8s.hursley.ibm.com/galasadev/galasa-maven-mvp

obr:
  repository: harbor-cicsk8s.hursley.ibm.com/galasadev/galasa-maven-obr

javadoc:
  repository: harbor-cicsk8s.hursley.ibm.com/galasadev/galasa-maven-javadoc

apidocs:
  repository: harbor-cicsk8s.hursley.ibm.com/galasadev/galasa-javadocs

p2:
  repository: harbor-cicsk8s.hursley.ibm.com/galasadev/galasa-p2

simplatform:
  repository: harbor-cicsk8s.hursley.ibm.com/galasadev/galasa-maven-simplatform

service:
  type: ClusterIP
  port: 80

nodeSelector: 
  kubernetes.io/arch: amd64

fullVersion: true

ingress:
  enabled: true
