#
# Licensed Materials - Property of IBM
# 
# (c) Copyright IBM Corp. 2021.
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: snapshot-galasa
  namespace: galasa-tekton
spec:
  resources:
  - name: git-tekton
    type: git
  params:
  - name: distBranch
    type: string
  - name: oldBranch
    type: string
  tasks:
  - name: snapshot-obr
    taskRef:
      name: snapshot-repo
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: oldBranch
      value: $(params.oldBranch)
    - name: image
      value: galasa-maven-obr
    resources:
      inputs:
      - name: git-tekton
        resource: git-tekton
  - name: snapshot-mvp
    taskRef:
      name: snapshot-repo
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: oldBranch
      value: $(params.oldBranch)
    - name: image
      value: galasa-maven-mvp
    resources:
      inputs:
      - name: git-tekton
        resource: git-tekton
  - name: snapshot-isolated
    taskRef:
      name: snapshot-repo
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: oldBranch
      value: $(params.oldBranch)
    - name: image
      value: galasa-maven-isolated
    resources:
      inputs:
      - name: git-tekton
        resource: git-tekton
  - name: snapshot-boot-embedded
    taskRef:
      name: snapshot-generic
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: oldBranch
      value: $(params.oldBranch)
    - name: image
      value: galasa-boot-embedded-amd64
    resources:
      inputs:
      - name: git-tekton
        resource: git-tekton
  - name: snapshot-ibm-boot-embedded
    taskRef:
      name: snapshot-generic
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: oldBranch
      value: $(params.oldBranch)
    - name: image
      value: galasa-ibm-boot-embedded-amd64
    resources:
      inputs:
      - name: git-tekton
        resource: git-tekton
  - name: recycle-obr
    taskRef:
      name: recycle-deployment
    runAfter:
    - snapshot-obr
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-obr
  - name: recycle-mvp
    taskRef:
      name: recycle-deployment
    runAfter:
    - snapshot-mvp
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-mvp
  - name: recycle-isolated
    taskRef:
      name: recycle-deployment
    runAfter:
    - snapshot-isolated
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-isolated
