#
# Licensed Materials - Property of IBM
# 
# (c) Copyright IBM Corp. 2021.
#
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: snapshot-repo
  namespace: galasa-tekton
spec:
  resources:
    inputs:
      - name: git-tekton
        type: git
  params:
  - name: distBranch
    type: string
  - name: oldBranch
    type: string
  - name: image
    type: string
  - name: dockerRepo
    type: string
    default: nexus.cics-ts.hur.hdclab.intranet.ibm.com:8080
  steps: 
  - name: snap-repo
    workingDir: /workspace/git-tekton/snapshots
    image: $(params.dockerRepo)/library/kaniko-executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    command:
    - /kaniko/executor
    - --dockerfile=./DockerfileRepo
    - --context=/workspace/git-tekton/snapshots
    - --destination=$(params.dockerRepo)/galasadev/$(params.image):$(params.distBranch)
    - --oci-layout-path=/workspace/git-framework/docker/image-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --single-snapshot
    - --verbosity=info
    - --build-arg=dockerRepository=$(params.dockerRepo)
    - --build-arg=image=$(params.image)
    - --build-arg=branch=$(params.distBranch)
    - --build-arg=oldBranch=$(params.oldBranch)
