apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: galasa-build-source-pvc
  namespace: tekton
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: rbd