apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: docker-build-publish
spec:
  resources:
  - name: git
    type: git
  params:
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: src
    - name: imageUrl
      description: Image name including repository
    - name: imageTag
      description: Image tag
      default: "latest"
  tasks:
    - name: source-to-image
      taskRef:
        name: docker-build
      resources:
        inputs:
        - name: git
          resource: git
      params:
        - name: CONTEXT
          value: $(params.pathToContext)
        - name: IMAGE
          value: $(params.imageUrl):$(params.imageTag)