apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven-repo-build
spec:
  resources:
  - name: git-maven
    type: git
  params:
  - name: distBranch
    type: string
  - name: version
    type: string
  - name: gradleVersion
    type: string
  - name: noPush
    type: string
    default: ""
  - name: jacocoEnabled
    type: string
    default: "false"
  - name: isRelease
    type: string
    default: "false"
  tasks:
  - name: maven-compile
    taskRef:
      name: maven-repo-build
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.version)
    - name: gradleVersion
      value: $(params.gradleVersion)
    - name: noPush
      value: $(params.noPush)
    - name: jacocoEnabled
      value: $(params.jacocoEnabled)
    - name: isRelease
      value: $(params.isRelease)
    resources:
      inputs:
      - name: git-maven
        resource: git-maven
  - name: recycle-maven
    taskRef:
      name: recycle-deployment
    runAfter:
    - maven-compile
    when:
    - input: "$(params.noPush)"
      operator: notin
      values: ["--no-push"]
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-maven
