apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: runtime-build
spec:
  resources:
  - name: git-framework
    type: git
  - name: git-extensions
    type: git
  - name: git-managers
    type: git
  - name: git-obr
    type: git
  - name: git-docker
    type: git
  - name: git-isolated
    type: git
  params:
  - name: distBranch
    type: string
  - name: version
    type: string
  - name: mavenVersion
    type: string
  - name: jacocoEnabled
    type: string
    default: "true"
  - name: isRelease
    type: string
    default: "false"
  tasks:
  - name: framework-build
    taskRef:
      name: framework-repo-build
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.version)
    - name: mavenVersion
      value: $(params.mavenVersion)
    - name: mavenSourceRepo
      value: http://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/maven
    - name: jacocoEnabled
      value: $(params.jacocoEnabled)
    - name: isRelease
      value: $(params.isRelease)
    resources:
      inputs:
      - name: git-framework
        resource: git-framework
  - name: recycle-framework
    taskRef:
      name: recycle-deployment
    runAfter:
    - framework-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-framework
  - name: extensions-build
    taskRef:
      name: extensions-repo-build
    runAfter:
    - recycle-framework
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.version)
    - name: frameworkVersion
      value: $(params.version)
    - name: frameworkSourceRepo
      value: http://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/framework/
    - name: jacocoEnabled
      value: $(params.jacocoEnabled)
    - name: isRelease
      value: $(params.isRelease)
    resources:
      inputs:
      - name: git-extensions
        resource: git-extensions
  - name: recycle-extensions
    taskRef:
      name: recycle-deployment
    runAfter:
    - extensions-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-extensions
  - name: managers-build
    taskRef:
      name: managers-repo-build
    runAfter:
    - recycle-extensions
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.version)
    - name: extensionsVersion
      value: $(params.version)
    - name: extensionsSourceRepo
      value: http://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/extensions/
    - name: jacocoEnabled
      value: $(params.jacocoEnabled)
    - name: isRelease
      value: $(params.isRelease)
    resources:
      inputs:
      - name: git-managers
        resource: git-managers
  - name: recycle-managers
    taskRef:
      name: recycle-deployment
    runAfter:
    - managers-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-managers
  - name: obr-build
    taskRef:
      name: obr-repo-build
    runAfter:
    - recycle-managers
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.version)
    - name: managersVersion
      value: $(params.version)
    - name: managersSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/managers/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    resources:
      inputs:
      - name: git-obr
        resource: git-obr
  - name: recycle-obr
    taskRef:
      name: recycle-deployment
    runAfter:
    - obr-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-obr
  - name: obr-embedded
    taskRef:
      name: obr-generic-build
    runAfter:
    - recycle-obr
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.version)
    - name: obrSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/obr/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    resources:
      inputs:
      - name: git-docker
        resource: git-docker
  - name: javadoc-build
    taskRef:
      name: javadoc-build
    runAfter:
    - recycle-obr
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.version)
    - name: managersSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/managers/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    resources:
      inputs:
      - name: git-obr
        resource: git-obr
  - name: recycle-javadoc
    taskRef:
      name: recycle-deployment
    runAfter:
    - javadoc-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-javadoc
  - name: recycle-apidoc
    taskRef:
      name: recycle-deployment
    runAfter:
    - javadoc-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-apidocs
  - name: mvp-build
    taskRef:
      name: mvp-build
    runAfter:
    - recycle-javadoc
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.version)
    - name: simplatformSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/simplatform/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    - name: runtimeSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/obr/
    - name: eclipseSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/eclipse/
    - name: javadocSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/javadoc/
    - name: docsSourceRepo
      value: https://nexus.galasa.dev/repository/docs/
    resources:
      inputs:
      - name: git-isolated
        resource: git-isolated
      - name: git-obr
        resource: git-obr
  - name: recycle-mvp-maven
    taskRef:
      name: recycle-deployment
    runAfter:
    - mvp-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-mvp
  - name: isolated-build
    taskRef:
      name: isolated-build
    runAfter:
    - recycle-javadoc
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.version)
    - name: simplatformSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/simplatform/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    - name: runtimeSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/obr/
    - name: eclipseSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/eclipse/
    - name: javadocSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/javadoc/
    - name: docsSourceRepo
      value: https://nexus.galasa.dev/repository/docs/
    resources:
      inputs:
      - name: git-isolated
        resource: git-isolated
      - name: git-obr
        resource: git-obr
  - name: recycle-isolated-maven
    taskRef:
      name: recycle-deployment
    runAfter:
    - isolated-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-isolated
  - name: docker-operator-build
    taskRef:
      name: docker-operator-build
    runAfter:
    - recycle-extensions
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.version)
    - name: extensionsSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/extensions/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    resources:
      inputs:
      - name: git-docker
        resource: git-docker