apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: obr-repo-build
spec:
  resources:
  - name: git-obr
    type: git
  params:
  - name: branch
    type: string
  - name: version
    type: string
  tasks:
  - name: obr-build
    taskRef:
      name: obr-repo-build
    params:
    - name: branch
      value: $(params.branch)
    - name: version
      value: $(params.version)
    - name: managersVersion
      value: $(params.version)
    - name: managersSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.branch)/maven/managers/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    resources:
      inputs:
      - name: git-obr
        resource: git-obr
  - name: recycle-obr
    taskRef:
      name: recycle-deployment
    runAfter:
    - obr-build
    params:
    - name: namespace
      value: galasa-prod
    - name: deployment
      value: maven-$(params.branch)-obr
