apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mvp-isolated-pr
spec:
  resources:
  - name: git-isolated
    type: git
  - name: git-obr
    type: git
  params:
  - name: distBranch
    type: string
  - name: version
    type: string
  - name: noPush
    type: string
    default: "--no-push"
  tasks:
  - name: isolated-build
    taskRef:
      name: isolated-build
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.version)
    - name: simplatformSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/simplatform/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    - name: runtimeSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/obr/
    - name: eclipseSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/eclipse/
    - name: noPush
      value: $(params.noPush)
    resources:
      inputs:
      - name: git-isolated
        resource: git-isolated
      - name: git-obr
        resource: git-obr
  - name: mvp-build
    taskRef:
      name: mvp-build
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.version)
    - name: simplatformSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/simplatform/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    - name: runtimeSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/obr/
    - name: eclipseSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/eclipse/
    - name: noPush
      value: $(params.noPush)
    resources:
      inputs:
      - name: git-isolated
        resource: git-isolated
      - name: git-obr
        resource: git-obr
