#
# Licensed Materials - Property of IBM
# 
# (c) Copyright IBM Corp. 2021.
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: openapi-build
  namespace: galasa-tekton
spec:
  resources:
  - name: git-openapi
    type: git
  - name: git-openapi-go
    type: git
  tasks:
  - name: build-openapi
    taskRef:
      name: openapi-repo-build
    resources:
      inputs:
      - name: git-openapi
        resource: git-openapi
      - name: git-openapi-go
        resource: git-openapi-go
