apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gradle-repo-build
spec:
  resources:
  - name: git-gradle
    type: git
  params:
  - name: distBranch
    type: string
  - name: version
    type: string
  - name: noPush
    type: string
    default: ""
  - name: jacocoEnabled
    type: string
    default: "false"
  - name: isRelease
    type: string
    default: "false"
  results:
  - name: image
    description: The Docker image produced by this pipeline
    value: $(tasks.gradle-compile.results.image)
  tasks:
  - name: gradle-compile
    taskRef:
      name: gradle-repo-build
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.version)
    - name: noPush
      value: $(params.noPush)
    - name: jacocoEnabled
      value: $(params.jacocoEnabled)
    - name: isRelease
      value: $(params.isRelease)
    resources:
      inputs:
      - name: git-gradle
        resource: git-gradle
  - name: recycle-deployment
    taskRef:
      name: recycle-deployment
    runAfter:
    - gradle-compile
    when:
    - input: "$(params.noPush)"
      operator: notin
      values: ["--no-push"]
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-gradle
