apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: staging-build
spec:
  resources:
  - name: git-gradle
    type: git
  - name: git-maven
    type: git
  - name: git-framework
    type: git
  - name: git-extensions
    type: git
  - name: git-managers
    type: git
  - name: git-obr
    type: git
  - name: git-docker
    type: git
  - name: git-isolated
    type: git
  - name: git-simplatform
    type: git
  - name: git-eclipse
    type: git
  params:
  - name: distBranch
    type: string
  - name: gradleVersion
    type: string
  - name: mavenVersion
    type: string
  - name: runtimeVersion
    type: string
  - name: eclipseVersion
    type: string
  - name: simplatformVersion
    type: string
  - name: noPush
    type: string
    default: ""
  - name: jacocoEnabled
    type: string
    default: "false"
  - name: isRelease
    type: string
    default: "true"
  tasks:
  - name: gradle-compile
    taskRef:
      name: gradle-repo-build
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.gradleVersion)
    - name: noPush
      value: $(params.noPush)
    - name: jacocoEnabled
      value: $(params.jacocoEnabled)
    - name: isRelease
      value: $(params.isRelease)
    resources:
      inputs:
      - name: git-gradle
        resource: git-gradle
  - name: gradle-recycle
    taskRef:
      name: recycle-deployment
    runAfter:
    - gradle-compile
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-gradle
  - name: maven-compile
    taskRef:
      name: maven-repo-build
    runAfter:
    - gradle-recycle
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.mavenVersion)
    - name: gradleVersion
      value: $(params.gradleVersion)
    - name: noPush
      value: $(params.noPush)
    - name: jacocoEnabled
      value: $(params.jacocoEnabled)
    - name: isRelease
      value: $(params.isRelease)
    resources:
      inputs:
      - name: git-maven
        resource: git-maven
  - name: maven-recycle
    taskRef:
      name: recycle-deployment
    runAfter:
    - maven-compile
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-maven
  - name: framework-build
    taskRef:
      name: framework-repo-build
    runAfter:
    - maven-recycle
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.runtimeVersion)
    - name: mavenVersion
      value: $(params.mavenVersion)
    - name: mavenSourceRepo
      value: http://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/maven
    - name: jacocoEnabled
      value: $(params.jacocoEnabled)
    - name: isRelease
      value: $(params.isRelease)
    resources:
      inputs:
      - name: git-framework
        resource: git-framework
  - name: framework-recycle
    taskRef:
      name: recycle-deployment
    runAfter:
    - framework-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-framework
  - name: extensions-build
    taskRef:
      name: extensions-repo-build
    runAfter:
    - framework-recycle
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.runtimeVersion)
    - name: frameworkVersion
      value: $(params.runtimeVersion)
    - name: frameworkSourceRepo
      value: http://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/framework/
    - name: jacocoEnabled
      value: $(params.jacocoEnabled)
    - name: isRelease
      value: $(params.isRelease)
    resources:
      inputs:
      - name: git-extensions
        resource: git-extensions
  - name: extensions-recycle
    taskRef:
      name: recycle-deployment
    runAfter:
    - extensions-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-extensions
  - name: managers-build
    taskRef:
      name: managers-repo-build
    runAfter:
    - extensions-recycle
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.runtimeVersion)
    - name: extensionsVersion
      value: $(params.runtimeVersion)
    - name: extensionsSourceRepo
      value: http://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/extensions/
    - name: jacocoEnabled
      value: $(params.jacocoEnabled)
    - name: isRelease
      value: $(params.isRelease)
    resources:
      inputs:
      - name: git-managers
        resource: git-managers
  - name: managers-recycle
    taskRef:
      name: recycle-deployment
    runAfter:
    - managers-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-managers
  - name: obr-build
    taskRef:
      name: obr-repo-build
    runAfter:
    - managers-recycle
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.runtimeVersion)
    - name: managersVersion
      value: $(params.runtimeVersion)
    - name: managersSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/managers/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    resources:
      inputs:
      - name: git-obr
        resource: git-obr
  - name: obr-recycle
    taskRef:
      name: recycle-deployment
    runAfter:
    - obr-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-obr
  - name: obr-embedded
    taskRef:
      name: obr-generic-build
    runAfter:
    - obr-recycle
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.runtimeVersion)
    - name: obrSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/obr/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    resources:
      inputs:
      - name: git-docker
        resource: git-docker
  - name: javadoc-build
    taskRef:
      name: javadoc-build
    runAfter:
    - obr-recycle
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.runtimeVersion)
    - name: managersSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/managers/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    resources:
      inputs:
      - name: git-obr
        resource: git-obr
  - name: javadoc-recycle
    taskRef:
      name: recycle-deployment
    runAfter:
    - javadoc-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-javadoc
  - name: apidoc-recycle
    taskRef:
      name: recycle-deployment
    runAfter:
    - javadoc-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-apidocs
  - name: simplatform-build
    taskRef:
      name: simplatform-repo-build
    runAfter:
    - managers-recycle
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.simplatformVersion)
    - name: managersSourceRepo
      value: http://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/managers/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    resources:
      inputs:
      - name: git-simplatform
        resource: git-simplatform
  - name: simplatform-recycle
    taskRef:
      name: recycle-deployment
    runAfter:
    - simplatform-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-simplatform
  - name: eclipse-build
    taskRef:
      name: eclipse-repo-build
    runAfter:
    - obr-recycle
    - simplatform-recycle
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.eclipseVersion)
    - name: eclipseRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/photon/
    - name: simplatformSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/simplatform/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    - name: runtimeSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/obr/
    resources:
      inputs:
      - name: git-eclipse
        resource: git-eclipse
  - name: eclipse-maven-recycle
    taskRef:
      name: recycle-deployment
    runAfter:
    - eclipse-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-eclipse
  - name: eclipse-p2-recycle
    taskRef:
      name: recycle-deployment
    runAfter:
    - eclipse-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: p2-$(params.distBranch)
  - name: mvp-build
    taskRef:
      name: mvp-build
    runAfter:
    - obr-recycle
    - javadoc-recycle
    - eclipse-maven-recycle
    - simplatform-recycle
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.runtimeVersion)
    - name: simplatformSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/simplatform/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    - name: runtimeSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/obr/
    - name: eclipseSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/eclipse/
    - name: javadocSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/javadoc/
    - name: docsSourceRepo
      value: https://nexus.galasa.dev/repository/docs/
    resources:
      inputs:
      - name: git-isolated
        resource: git-isolated
      - name: git-obr
        resource: git-obr
  - name: mvp-maven-recycle
    taskRef:
      name: recycle-deployment
    runAfter:
    - mvp-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-mvp
  - name: isolated-build
    taskRef:
      name: isolated-build
    runAfter:
    - obr-recycle
    - javadoc-recycle
    - eclipse-maven-recycle
    - simplatform-recycle
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.runtimeVersion)
    - name: simplatformSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/simplatform/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    - name: runtimeSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/obr/
    - name: eclipseSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/eclipse/
    - name: javadocSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/javadoc/
    - name: docsSourceRepo
      value: https://nexus.galasa.dev/repository/docs/
    resources:
      inputs:
      - name: git-isolated
        resource: git-isolated
      - name: git-obr
        resource: git-obr
  - name: isolated-maven-recycle
    taskRef:
      name: recycle-deployment
    runAfter:
    - isolated-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-isolated
  - name: docker-operator-build
    taskRef:
      name: docker-operator-build
    runAfter:
    - extensions-recycle
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: version
      value: $(params.runtimeVersion)
    - name: extensionsSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/extensions/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    resources:
      inputs:
      - name: git-docker
        resource: git-docker
