#
# Copyright contributors to the Galasa project 
#
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: isolated-build-
spec:
  params:
  - name: isRelease
    value: "true"
  pipelineRef:
    name: isolated-repo-build
  serviceAccountName: build-bot
  podTemplate:
    nodeSelector:
      beta.kubernetes.io/arch: amd64
  workspaces:
  - name: git-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
