#
# Copyright contributors to the Galasa project 
#
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: runtime-build-
spec:
  params:
  - name: isRelease
    value: "true"
  pipelineRef:
    name: runtime-build
  serviceAccountName: build-bot
  podTemplate:
    nodeSelector:
      beta.kubernetes.io/arch: amd64
    volumes:
    - name: gpgkey
      secret:
        secretName: gpgkey
    - name: gpggradle
      secret:
        secretName: gpggradle
    - name: mavengpg
      secret:
        secretName: mavengpg
  workspaces:
  - name: git-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
