{{- if .Values.fullVersion }}
{{- if .Values.ingress.enabled }}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: p2-{{ .Release.Name }}-i443
  annotations:
    kubernetes.io/ingress.class: nginx-cit
spec:
  rules:
    - http:
        paths:
          - path: /galasadev/{{ .Release.Name}}/p2
            backend:
              serviceName: p2-{{ .Release.Name}}
              servicePort: 80
{{- end }}
{{- end }}