apiVersion: galasa.dev/v1alpha
kind: Release
metadata:
  name: galasa-release
release:
  version: 0.16.0
framework:
  bundles:
  - artifact: dev.galasa
    version: 0.15.0
    bom: true
    mvp: true
    javadoc: true
  - artifact: dev.galasa.framework
    version: 0.15.0
    mvp: true
api:
  bundles:
  - artifact: dev.galasa.framework.api.ras
    version: 0.15.0
managers:
  bundles:
  - artifact: dev.galasa.zos3270.managers
    version: 0.16.0
    mvp: true
external:
  bundles:
  - group: commons-io
    artifact: commons-io
    version: 2.6
    obr: true
    mvp: true
    isolated: true