#
# Copyright contributors to the Galasa project 
#
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: main-isolated-
spec:
  params:
  - name: distBranch
    value: main
  - name: refspec
    value: +refs/heads/main:refs/heads/main
  pipelineRef:
    name: isolated-repo-build
  serviceAccountName: build-bot
  podTemplate:
    nodeSelector:
      beta.kubernetes.io/arch: amd64
      platform: hdc
  workspaces:
  - name: git-workspace
    volumeClaimTemplate:
      spec:
        storageClassName: rbd
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
