{{- if .Values.fullVersion }}
{{- if .Values.ingress.enabled }}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: maven-{{ .Release.Name }}-maven
  annotations:
    kubernetes.io/ingress.class: nginx-cit-insecure
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  rules:
    - http:
        paths:
          - path: /galasadev/{{ .Release.Name}}/maven/maven
            backend:
              serviceName: maven-{{ .Release.Name}}-maven
              servicePort: 80
{{- end }}
{{- end }}