#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven-repo-build
spec:
  workspaces:
  - name: git-workspace
    optional: false
  params:
  - name: distBranch
    type: string
    default: {{ .Release.Name }}
  - name: refspec
    type: string
    default: +refs/heads/{{ .Release.Name }}:refs/heads/{{ .Release.Name }}
  - name: noPush
    type: string
    default: ""
  - name: jacocoEnabled
    type: string
    default: "false"
  - name: isRelease
    type: string
    default: "false"
  tasks:
  - name: clone-maven
    taskRef: 
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/maven
    - name: revision
      value: $(params.distBranch)
    - name: refspec
      value: $(params.refspec)
    - name: depth
      value: "99999999"
    - name: subdirectory
      value: maven
    workspaces:
     - name: output
       workspace: git-workspace
  - name: maven-compile
    taskRef:
      name: maven-repo-build
    runAfter:
    - clone-maven
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: noPush
      value: $(params.noPush)
    - name: jacocoEnabled
      value: $(params.jacocoEnabled)
    - name: isRelease
      value: $(params.isRelease)
    workspaces:
     - name: git-workspace
       workspace: git-workspace
  - name: recycle-maven
    taskRef:
      name: recycle-deployment
    runAfter:
    - maven-compile
    when:
    - input: "$(params.noPush)"
      operator: notin
      values: ["--no-push"]
    params:
    - name: namespace
      value: galasa-branch-{{ .Release.Name }}
    - name: deployment
      value: maven-$(params.distBranch)-maven
