{{- if .Values.fullVersion }}
apiVersion: v1
kind: Service
metadata:
  name: maven-{{ .Release.Name }}-maven
  labels:
    app: maven-{{ .Release.Name }}-maven
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: maven-{{ .Release.Name }}-maven
{{- end }}