#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: docker-operator-build
spec:
  workspaces:
  - name: git-workspace
    optional: false
  params:
  - name: distBranch
    type: string
    default: {{ .Release.Name }}
  - name: refspec
    type: string
    default: +refs/heads/{{ .Release.Name }}:refs/heads/{{ .Release.Name }}
  - name: noPush
    type: string
    default: ""
  tasks:
  - name: clone-docker
    taskRef: 
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/docker
    - name: revision
      value: $(params.distBranch)
    - name: depth
      value: "1"
    - name: subdirectory
      value: docker
    workspaces:
     - name: output
       workspace: git-workspace
  - name: docker-operator-build
    taskRef:
      name: docker-operator-build
    runAfter:
    - clone-docker
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: extensionsSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/extensions/
    - name: mavenCentralRepo
      value: https://artifactory-cicsk8s.hursley.ibm.com/artifactory/maven-proxy/
    - name: noPush
      value: $(params.noPush)
    workspaces:
     - name: git-workspace
       workspace: git-workspace
