#
# Licensed Materials - Property of IBM
# 
# (c) Copyright IBM Corp. 2021.
#
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: obr-repo-build
  namespace: galasa-tekton
spec:
  resources:
    inputs:
      - name: git-obr
        type: git
  params:
  - name: distBranch
    type: string
  - name: mavenCentralRepo
    type: string
    default: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
  - name: managersSourceRepo
    type: string
    default: https://repo.maven.apache.org/maven2/
  - name: dockerRepo
    type: string
    default: nexus.cics-ts.hur.hdclab.intranet.ibm.com:8080
  - name: noPush
    type: string
    default: ""
  steps:
  - name: gpgdirectory
    workingDir: /workspace
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - mkdir
    - /workspace/gpg
  - name: import-gpg
    workingDir: /workspace
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - gpg
    - --homedir
    - /workspace/gpg
    - --pinentry-mode
    - loopback
    - --passphrase-file
    - /root/mavengpg/galasa.passphrase
    - --import
    - /root/mavengpg/galasa.gpg
    volumeMounts:
    - name: mavengpg
      mountPath: /root/mavengpg
  - name: copy-settings
    workingDir: /workspace
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - cp
    - /root/mavengpg/settings.xml
    - /workspace/gpg/settings.xml
    volumeMounts:
    - name: mavengpg
      mountPath: /root/mavengpg
  - name: get-commit
    workingDir: /workspace/git-obr
    image: $(params.dockerRepo)/galasa/galasa-build
    script: |
      #!/bin/sh
      set +e
      COMMIT="$(git log --format="%H" -n 1)"
      echo $COMMIT > /workspace/git-obr/docker/obr.githash
      echo commit is $COMMIT
  - name: generate-bom
    workingDir: /workspace/git-obr/galasa-bom
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - galasabld 
    - template 
    - --releaseMetadata
    - ../release.yaml 
    - --template
    - pom.template 
    - --output
    - pom.xml 
    - --bom
  - name: list-bom
    workingDir: /workspace/git-obr/galasa-bom
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - cat
    - pom.xml
  - name: bom-build
    workingDir: /workspace/git-obr/galasa-bom
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - mvn
    - -Dgalasa.release.repo=file:/workspace/git-obr/docker/repo/
    - -Dgalasa.source.repo=$(params.managersSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - --settings
    - /workspace/gpg/settings.xml
    - -B
    - -e
    - -fae
    - deploy
  - name: generate-obr
    workingDir: /workspace/git-obr/dev.galasa.uber.obr
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - galasabld 
    - template 
    - --releaseMetadata
    - ../release.yaml 
    - --template
    - pom.template 
    - --output
    - pom.xml 
    - --obr
  - name: list-obr
    workingDir: /workspace/git-obr/dev.galasa.uber.obr
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - cat
    - pom.xml
  - name: obr-build
    workingDir: /workspace/git-obr/dev.galasa.uber.obr
    image: $(params.dockerRepo)/galasa/galasa-build
    command:
    - mvn
    - -Dgalasa.release.repo=file:/workspace/git-obr/docker/repo/
    - -Dgalasa.source.repo=$(params.managersSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - --settings
    - /workspace/gpg/settings.xml
    - -B
    - -e
    - -fae
    - deploy
  - name: docker-build
    workingDir: /workspace/git-obr/docker
    image: $(params.dockerRepo)/library/kaniko-executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    command:
    - /kaniko/executor
    - --dockerfile=./Dockerfile
    - --context=/workspace/git-obr/docker
    - --destination=$(params.dockerRepo)/galasadev/galasa-maven-obr:$(params.distBranch)
    - $(params.noPush)
    - --oci-layout-path=/workspace/git-obr/docker/image-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --single-snapshot
    - --verbosity=info
    - --build-arg=dockerRepository=$(params.dockerRepo)
    - --build-arg=branch=$(params.distBranch)
