#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: runtime-build
spec:
  workspaces:
  - name: git-workspace
    optional: false
  params:
  - name: distBranch
    type: string
    default: {{ .Release.Name }}
  - name: refspec
    type: string
    default: +refs/heads/{{ .Release.Name }}:refs/heads/{{ .Release.Name }}
  - name: jacocoEnabled
    type: string
    default: "true"
  - name: isRelease
    type: string
    default: "false"
  tasks:
  - name: clone-framework
    taskRef: 
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/framework
    - name: revision
      value: $(params.distBranch)
    - name: depth
      value: "99999999"
    - name: subdirectory
      value: framework
    workspaces:
     - name: output
       workspace: git-workspace
  - name: clone-extensions
    taskRef: 
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/extensions
    - name: revision
      value: $(params.distBranch)
    - name: depth
      value: "99999999"
    - name: subdirectory
      value: extensions
    workspaces:
     - name: output
       workspace: git-workspace
  - name: clone-managers
    taskRef: 
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/managers
    - name: revision
      value: $(params.distBranch)
    - name: depth
      value: "99999999"
    - name: subdirectory
      value: managers
    workspaces:
     - name: output
       workspace: git-workspace
  - name: clone-obr
    taskRef: 
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/obr
    - name: revision
      value: $(params.distBranch)
    - name: refspec
      value: $(params.refspec)
    - name: depth
      value: "99999999"
    - name: subdirectory
      value: obr
    workspaces:
     - name: output
       workspace: git-workspace
  - name: clone-docker
    taskRef: 
      name: git-clone
    params:
    - name: url
      value: https://github.com/galasa-dev/docker
    - name: revision
      value: $(params.distBranch)
    - name: refspec
      value: $(params.refspec)
    - name: depth
      value: "99999999"
    - name: subdirectory
      value: docker
    workspaces:
     - name: output
       workspace: git-workspace
  - name: framework-build
    taskRef:
      name: framework-repo-build
    runAfter:
    - clone-framework
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: mavenSourceRepo
      value: http://maven-$(params.distBranch)-maven.galasa-development.svc.cluster.local/galasadev/$(params.distBranch)/maven/maven
    - name: jacocoEnabled
      value: $(params.jacocoEnabled)
    - name: isRelease
      value: $(params.isRelease)
    workspaces:
     - name: git-workspace
       workspace: git-workspace
  - name: recycle-framework
    taskRef:
      name: recycle-deployment
    runAfter:
    - framework-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-framework
  - name: extensions-build
    taskRef:
      name: extensions-repo-build
    runAfter:
    - recycle-framework
    - clone-extensions
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: frameworkSourceRepo
      value: http://maven-$(params.distBranch)-framework.galasa-development.svc.cluster.local/galasadev/$(params.distBranch)/maven/framework/
    - name: jacocoEnabled
      value: $(params.jacocoEnabled)
    - name: isRelease
      value: $(params.isRelease)
    workspaces:
     - name: git-workspace
       workspace: git-workspace
  - name: recycle-extensions
    taskRef:
      name: recycle-deployment
    runAfter:
    - extensions-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-extensions
  - name: managers-build
    taskRef:
      name: managers-repo-build
    runAfter:
    - recycle-extensions
    - clone-managers
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: extensionsSourceRepo
      value: http://maven-$(params.distBranch)-extensions.galasa-development.svc.cluster.local/galasadev/$(params.distBranch)/maven/extensions/
    - name: jacocoEnabled
      value: $(params.jacocoEnabled)
    - name: isRelease
      value: $(params.isRelease)
    workspaces:
     - name: git-workspace
       workspace: git-workspace
  - name: recycle-managers
    taskRef:
      name: recycle-deployment
    runAfter:
    - managers-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-managers
  - name: obr-build
    taskRef:
      name: obr-repo-build
    runAfter:
    - recycle-managers
    - clone-obr
    - clone-framework
    - clone-extensions
    - clone-managers
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: managersSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/managers/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    workspaces:
     - name: git-workspace
       workspace: git-workspace
  - name: recycle-obr
    taskRef:
      name: recycle-deployment
    runAfter:
    - obr-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-obr
  - name: obr-embedded
    taskRef:
      name: obr-generic-build
    runAfter:
    - recycle-obr
    - clone-docker
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: obrSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/obr/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    workspaces:
     - name: git-workspace
       workspace: git-workspace
  - name: javadoc-build
    taskRef:
      name: javadoc-build
    runAfter:
    - recycle-obr
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: managersSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/managers/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    workspaces:
     - name: git-workspace
       workspace: git-workspace
  - name: recycle-javadoc
    taskRef:
      name: recycle-deployment
    runAfter:
    - javadoc-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-javadoc
  - name: recycle-apidoc
    taskRef:
      name: recycle-deployment
    runAfter:
    - javadoc-build
    params:
    - name: namespace
      value: galasa-development
    - name: deployment
      value: maven-$(params.distBranch)-apidocs
  - name: docker-operator-build
    taskRef:
      name: docker-operator-build
    runAfter:
    - recycle-extensions
    - clone-docker
    params:
    - name: distBranch
      value: $(params.distBranch)
    - name: extensionsSourceRepo
      value: https://cicscit.hursley.ibm.com/galasadev/$(params.distBranch)/maven/extensions/
    - name: mavenCentralRepo
      value: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
    workspaces:
     - name: git-workspace
       workspace: git-workspace
