#
# Copyright contributors to the Galasa project 
#
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: eclipse-repo-build
spec:
  workspaces:
  - name: git-workspace
    optional: false
    mountpath: /workspace/git
  params:
  - name: distBranch
    type: string
  - name: mavenBaseVersion
    type: string
    default: 0.16.0
  - name: mavenCentralRepo
    type: string
    default: https://nexus.cics-ts.hur.hdclab.intranet.ibm.com/repository/proxy/
  - name: runtimeSourceRepo
    type: string
    default: https://repo.maven.apache.org/maven2/
  - name: simplatformSourceRepo
    type: string
    default: https://repo.maven.apache.org/maven2/
  - name: eclipseRepo
    type: string
    default: http://download.eclipse.org/releases/photon
  - name: dockerRepo
    type: string
    default: harbor-cicsk8s.hursley.ibm.com
  - name: noPush
    type: string
    default: ""
  steps:
  - name: maven-build-eclipse
    workingDir: /workspace/git/eclipse/galasa-eclipse-parent
    image: $(params.dockerRepo)/galasadev/galasa-build
    command:
    - mvn
    - -Dgpg.skip=true
    - -Dgalasa.release.repo=file:/workspace/git/eclipse/docker/repo
    - -Dgalasa.runtime.repo=$(params.runtimeSourceRepo)
    - -Dgalasa.simplatform.repo=$(params.simplatformSourceRepo)
    - -Dgalasa.central.repo=$(params.mavenCentralRepo)
    - -Dgalasa.eclipse.repo=$(params.eclipseRepo)
    - -B
    - -e
    - -fae
    - deploy
  - name: docker-build-eclipse-repo
    workingDir: /workspace/git/eclipse/docker
    image: $(params.dockerRepo)/common/kaniko-project/executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/creds/.docker
    command:
    - /kaniko/executor
    - --dockerfile=./Dockerfile
    - --context=/workspace/git/eclipse/docker
    - --destination=$(params.dockerRepo)/galasadev/galasa-maven-eclipse:$(params.distBranch)
    - $(params.noPush)
    - --oci-layout-path=/workspace/git/eclipse/docker/image-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --single-snapshot
    - --verbosity=info
    - --build-arg=dockerRepository=$(params.dockerRepo)
    - --build-arg=baseVersion=$(params.mavenBaseVersion)
    - --build-arg=branch=$(params.distBranch)
    - --build-arg=gitHash=$(resources.inputs.git/eclipse.commit)
  - name: docker-build-eclipse-p2
    workingDir: /workspace/git/eclipse/galasa-eclipse-parent/dev.galasa.eclipse.site
    image: $(params.dockerRepo)/common/kaniko-project/executor:latest
    env:
    - name: DOCKER_CONFIG
      value: /tekton/creds/.docker
    command:
    - /kaniko/executor
    - --dockerfile=./Dockerfile
    - --context=/workspace/git/eclipse/galasa-eclipse-parent/dev.galasa.eclipse.site
    - --destination=$(params.dockerRepo)/galasadev/galasa-p2:$(params.distBranch)
    - $(params.noPush)
    - --oci-layout-path=/workspace/git/eclipse/docker/image-digest
    - --skip-tls-verify
    - --skip-tls-verify-pull
    - --single-snapshot
    - --verbosity=info
    - --build-arg=dockerRepository=$(params.dockerRepo)/dockerhub
    - --build-arg=branch=$(params.distBranch)
    - --build-arg=gitHash=$(resources.inputs.git.eclipse.commit)
    - --build-arg=baseVersion=$(params.mavenBaseVersion)
