{{- if .Values.fullVersion }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-{{ .Release.Name }}-eclipse
  labels:
    app: maven-{{ .Release.Name }}-eclipse
spec:
  replicas: {{ .Values.image.replicaCount }}
  selector:
    matchLabels:
        app: maven-{{ .Release.Name }}-eclipse
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: maven-{{ .Release.Name }}-eclipse
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.eclipse.repository }}:{{ .Release.Name }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}